# Render Blueprint for E-Commerce Application
# https://render.com/docs/blueprint-spec

services:
  # PostgreSQL Database
  - type: pserv
    name: ecommerce-postgres
    env: docker
    plan: starter  # Free tier available
    region: singapore
    databases:
      - name: ecommerce_db
        databaseName: ecommerce_prod
        user: ecommerce_user

  # Backend - Spring Boot API
  - type: web
    name: ecommerce-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    region: singapore
    plan: starter  # Free tier: 512 MB RAM, shared CPU
    healthCheckPath: /api/health
    envVars:
      # Database (auto-populated from database service)
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-postgres
          property: connectionString
      
      # Spring profiles
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      
      # JWT Configuration (REQUIRED: Set in Render Dashboard)
      - key: JWT_SECRET
        sync: false  # Set manually in dashboard
      - key: JWT_EXPIRATION
        value: "86400000"  # 24 hours
      - key: JWT_REFRESH_EXPIRATION
        value: "604800000"  # 7 days
      
      # Omise Payment Gateway
      # For DEMO/TESTING: Use test keys (default values below)
      # For PRODUCTION: Set live keys in Render Dashboard
      - key: OMISE_PUBLIC_KEY
        value: "pkey_test_65a692c53l3a7q5cheh"  # Test key (change to pkey_live_ for production)
      - key: OMISE_SECRET_KEY
        value: "skey_test_656kahkzqaoi7js7rjc"  # Test key (change to skey_live_ for production)
      - key: OMISE_API_VERSION
        value: "2019-05-29"
      
      # Application URLs (will be auto-updated after deployment)
      - key: API_BASE_URL
        value: https://ecommerce-backend.onrender.com
      - key: FRONTEND_URL
        value: https://ecommerce-frontend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://ecommerce-frontend.onrender.com
      
      # Upload directory
      - key: UPLOAD_DIR
        value: /app/uploads
    
    # Persistent disk for file uploads
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 1  # Free tier includes 1GB

  # Frontend - Next.js
  - type: web
    name: ecommerce-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    region: singapore
    plan: starter
    envVars:
      # API Configuration
      - key: NEXT_PUBLIC_API_URL
        value: https://ecommerce-backend.onrender.com/api
      - key: NEXT_PUBLIC_WS_URL
        value: wss://ecommerce-backend.onrender.com
      
      # Omise Payment (Public key only)
      # For DEMO/TESTING: Use test key (default value below)
      # For PRODUCTION: Set live key in Render Dashboard
      - key: NEXT_PUBLIC_OMISE_PUBLIC_KEY
        value: "pkey_test_65a692c53l3a7q5cheh"  # Test key (change to pkey_live_ for production)
      
      # Application URL
      - key: NEXT_PUBLIC_APP_URL
        value: https://ecommerce-frontend.onrender.com

# Notes:
# 1. Free tier services will spin down after 15 minutes of inactivity
# 2. First request after spin down may take 50+ seconds to respond
# 3. Database is persistent and will not spin down
# 4. To avoid spin down, upgrade to paid plan ($7/month minimum)
# 5. Update service URLs after first deployment
